[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_vault_2 = "3Q9kE4eqZXkKd8p6WQNjjAZf4x3TJ53joKVumW1acp3V"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/matthewpfeifer/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
